// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjurfuknkomngovjychd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqdXJmdWtua29tbmdvdmp5Y2hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MjEyMTgsImV4cCI6MjA2MDI5NzIxOH0.zJ8P3Yg3y04TJACRuALt1LwKW2eYfx1vkBt6cbT3Zqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});